name: me
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  animated_toggle_switch: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  get: 4.1.4
  google_fonts: ^2.1.0
  graphql_flutter: ^5.0.0
  hexcolor: ^2.0.5
  loading_animations: ^2.2.0
  rive: ^0.7.33
  thememode_selector:
    git:
      url: https://github.com/renankanu/thememode_selector.git
      ref: main
  url_launcher: ^6.0.8
  url_strategy: ^0.2.0
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/rive/
    - .env
