name: me
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_text_kit: ^4.2.1
  animated_toggle_switch: ^0.2.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.0
  font_awesome_flutter: ^9.1.0
  get: 4.1.4
  google_fonts: ^2.1.0
  graphql_flutter: ^5.0.0
  hexcolor: ^2.0.4
  loading_animations: ^2.2.0
  url_launcher: ^6.0.8
  url_strategy: ^0.2.0
  visibility_detector: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
